# Generated by Django 5.1.1 on 2024-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
